
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 22 17:34:18 CST 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Si = 11;
  public static final int Cambiar = 15;
  public static final int NumeroD = 30;
  public static final int Parentesis_c = 22;
  public static final int AND = 6;
  public static final int Parentesis_ap = 21;
  public static final int Numero = 29;
  public static final int OR = 7;
  public static final int Mas = 17;
  public static final int NOT = 8;
  public static final int flot = 4;
  public static final int Imprimir = 13;
  public static final int ERROR = 31;
  public static final int Para = 10;
  public static final int Identificador = 28;
  public static final int car = 3;
  public static final int Llave_c = 24;
  public static final int MenorQ = 20;
  public static final int Punto_c = 26;
  public static final int Funcion = 12;
  public static final int Main = 25;
  public static final int EOF = 0;
  public static final int MayorQ = 19;
  public static final int Escribir = 14;
  public static final int CONCA = 9;
  public static final int error = 1;
  public static final int Menos = 18;
  public static final int Punto = 27;
  public static final int Igual = 16;
  public static final int ent = 2;
  public static final int Llave_ap = 23;
  public static final int consta = 5;
}

